// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface buildingIDRequestMonitorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.buildingIDRequestMonitor)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();
}
