// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

/**
 * Protobuf type {@code livemonitor.buildingIDRequestMonitor}
 */
public  final class buildingIDRequestMonitor extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:livemonitor.buildingIDRequestMonitor)
    buildingIDRequestMonitorOrBuilder {
private static final long serialVersionUID = 0L;
  // Use buildingIDRequestMonitor.newBuilder() to construct.
  private buildingIDRequestMonitor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private buildingIDRequestMonitor() {
    buildingID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private buildingIDRequestMonitor(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            buildingID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.livemonitor.livemonitorImpl.internal_static_livemonitor_buildingIDRequestMonitor_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.livemonitor.livemonitorImpl.internal_static_livemonitor_buildingIDRequestMonitor_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.livemonitor.buildingIDRequestMonitor.class, ds.livemonitor.buildingIDRequestMonitor.Builder.class);
  }

  public static final int BUILDINGID_FIELD_NUMBER = 1;
  private int buildingID_;
  /**
   * <code>int32 buildingID = 1;</code>
   */
  public int getBuildingID() {
    return buildingID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (buildingID_ != 0) {
      output.writeInt32(1, buildingID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (buildingID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, buildingID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.livemonitor.buildingIDRequestMonitor)) {
      return super.equals(obj);
    }
    ds.livemonitor.buildingIDRequestMonitor other = (ds.livemonitor.buildingIDRequestMonitor) obj;

    boolean result = true;
    result = result && (getBuildingID()
        == other.getBuildingID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livemonitor.buildingIDRequestMonitor parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.livemonitor.buildingIDRequestMonitor prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code livemonitor.buildingIDRequestMonitor}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:livemonitor.buildingIDRequestMonitor)
      ds.livemonitor.buildingIDRequestMonitorOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.livemonitor.livemonitorImpl.internal_static_livemonitor_buildingIDRequestMonitor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.livemonitor.livemonitorImpl.internal_static_livemonitor_buildingIDRequestMonitor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.livemonitor.buildingIDRequestMonitor.class, ds.livemonitor.buildingIDRequestMonitor.Builder.class);
    }

    // Construct using ds.livemonitor.buildingIDRequestMonitor.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buildingID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.livemonitor.livemonitorImpl.internal_static_livemonitor_buildingIDRequestMonitor_descriptor;
    }

    @java.lang.Override
    public ds.livemonitor.buildingIDRequestMonitor getDefaultInstanceForType() {
      return ds.livemonitor.buildingIDRequestMonitor.getDefaultInstance();
    }

    @java.lang.Override
    public ds.livemonitor.buildingIDRequestMonitor build() {
      ds.livemonitor.buildingIDRequestMonitor result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.livemonitor.buildingIDRequestMonitor buildPartial() {
      ds.livemonitor.buildingIDRequestMonitor result = new ds.livemonitor.buildingIDRequestMonitor(this);
      result.buildingID_ = buildingID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.livemonitor.buildingIDRequestMonitor) {
        return mergeFrom((ds.livemonitor.buildingIDRequestMonitor)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.livemonitor.buildingIDRequestMonitor other) {
      if (other == ds.livemonitor.buildingIDRequestMonitor.getDefaultInstance()) return this;
      if (other.getBuildingID() != 0) {
        setBuildingID(other.getBuildingID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.livemonitor.buildingIDRequestMonitor parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.livemonitor.buildingIDRequestMonitor) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int buildingID_ ;
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public int getBuildingID() {
      return buildingID_;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder setBuildingID(int value) {
      
      buildingID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder clearBuildingID() {
      
      buildingID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:livemonitor.buildingIDRequestMonitor)
  }

  // @@protoc_insertion_point(class_scope:livemonitor.buildingIDRequestMonitor)
  private static final ds.livemonitor.buildingIDRequestMonitor DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.livemonitor.buildingIDRequestMonitor();
  }

  public static ds.livemonitor.buildingIDRequestMonitor getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<buildingIDRequestMonitor>
      PARSER = new com.google.protobuf.AbstractParser<buildingIDRequestMonitor>() {
    @java.lang.Override
    public buildingIDRequestMonitor parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new buildingIDRequestMonitor(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<buildingIDRequestMonitor> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<buildingIDRequestMonitor> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.livemonitor.buildingIDRequestMonitor getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

