// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface energyReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.energyReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 energyReading = 1;</code>
   */
  int getEnergyReading();

  /**
   * <pre>
   *google.protobuf.Timestamp timestamp = 3;//to add a timestamp
   * </pre>
   *
   * <code>int32 buildingID = 2;</code>
   */
  int getBuildingID();
}
