// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface energyReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.energyReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 energyReading = 1;</code>
   */
  int getEnergyReading();

  /**
   * <code>int32 buildingID = 2;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 date = 3;</code>
   */
  int getDate();
}
