// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public final class livemonitorImpl {
  private livemonitorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_buildingIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_buildingIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_energyReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_energyReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_waterReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_waterReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_temperatureReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_temperatureReadingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021livemonitor.proto\022\013livemonitor\"\'\n\021buil" +
      "dingIDRequest\022\022\n\nbuildingID\030\001 \001(\t\"B\n\025ene" +
      "rgyReadingResponse\022\025\n\renergyReading\030\001 \001(" +
      "\005\022\022\n\nbuildingID\030\002 \001(\t\"@\n\024waterReadingRes" +
      "ponse\022\024\n\014waterReading\030\001 \001(\005\022\022\n\nbuildingI" +
      "D\030\002 \001(\t\"L\n\032temperatureReadingResponse\022\032\n" +
      "\022temperatureReading\030\001 \001(\005\022\022\n\nbuildingID\030" +
      "\002 \001(\t2\245\002\n\renergyReading\022X\n\020getEnergyRead" +
      "ing\022\036.livemonitor.buildingIDRequest\032\".li" +
      "vemonitor.energyReadingResponse0\001\022V\n\017get" +
      "WaterReading\022\036.livemonitor.buildingIDReq" +
      "uest\032!.livemonitor.waterReadingResponse0" +
      "\001\022b\n\025getTemperatureReading\022\036.livemonitor" +
      ".buildingIDRequest\032\'.livemonitor.tempera" +
      "tureReadingResponse0\001B#\n\016ds.livemonitorB" +
      "\017livemonitorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_livemonitor_buildingIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_livemonitor_buildingIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_buildingIDRequest_descriptor,
        new java.lang.String[] { "BuildingID", });
    internal_static_livemonitor_energyReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_livemonitor_energyReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_energyReadingResponse_descriptor,
        new java.lang.String[] { "EnergyReading", "BuildingID", });
    internal_static_livemonitor_waterReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_livemonitor_waterReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_waterReadingResponse_descriptor,
        new java.lang.String[] { "WaterReading", "BuildingID", });
    internal_static_livemonitor_temperatureReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_livemonitor_temperatureReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_temperatureReadingResponse_descriptor,
        new java.lang.String[] { "TemperatureReading", "BuildingID", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
