// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public final class livemonitorImpl {
  private livemonitorImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_buildingIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_buildingIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_energyReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_energyReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_waterReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_waterReadingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livemonitor_temperatureReadingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livemonitor_temperatureReadingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021livemonitor.proto\022\013livemonitor\"\'\n\021buil" +
      "dingIDRequest\022\022\n\nbuildingID\030\001 \001(\005\"P\n\025ene" +
      "rgyReadingResponse\022\025\n\renergyReading\030\001 \001(" +
      "\005\022\022\n\nbuildingID\030\002 \001(\005\022\014\n\004date\030\003 \001(\005\"N\n\024w" +
      "aterReadingResponse\022\024\n\014waterReading\030\001 \001(" +
      "\005\022\022\n\nbuildingID\030\002 \001(\005\022\014\n\004date\030\003 \001(\005\"Z\n\032t" +
      "emperatureReadingResponse\022\032\n\022temperature" +
      "Reading\030\001 \001(\005\022\022\n\nbuildingID\030\002 \001(\005\022\014\n\004dat" +
      "e\030\003 \001(\0052\245\002\n\renergyReading\022X\n\020getEnergyRe" +
      "ading\022\036.livemonitor.buildingIDRequest\032\"." +
      "livemonitor.energyReadingResponse0\001\022V\n\017g" +
      "etWaterReading\022\036.livemonitor.buildingIDR" +
      "equest\032!.livemonitor.waterReadingRespons" +
      "e0\001\022b\n\025getTemperatureReading\022\036.livemonit" +
      "or.buildingIDRequest\032\'.livemonitor.tempe" +
      "ratureReadingResponse0\001B#\n\016ds.livemonito" +
      "rB\017livemonitorImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_livemonitor_buildingIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_livemonitor_buildingIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_buildingIDRequest_descriptor,
        new java.lang.String[] { "BuildingID", });
    internal_static_livemonitor_energyReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_livemonitor_energyReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_energyReadingResponse_descriptor,
        new java.lang.String[] { "EnergyReading", "BuildingID", "Date", });
    internal_static_livemonitor_waterReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_livemonitor_waterReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_waterReadingResponse_descriptor,
        new java.lang.String[] { "WaterReading", "BuildingID", "Date", });
    internal_static_livemonitor_temperatureReadingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_livemonitor_temperatureReadingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livemonitor_temperatureReadingResponse_descriptor,
        new java.lang.String[] { "TemperatureReading", "BuildingID", "Date", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
