// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface temperatureReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.temperatureReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperatureReading = 1;</code>
   */
  int getTemperatureReading();

  /**
   * <code>int32 buildingID = 2;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 date = 3;</code>
   */
  int getDate();
}
