// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface temperatureReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.temperatureReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temperatureReading = 1;</code>
   */
  int getTemperatureReading();

  /**
   * <pre>
   *google.protobuf.Timestamp timestamp = 3;//to add a timestamp
   * </pre>
   *
   * <code>string buildingID = 2;</code>
   */
  java.lang.String getBuildingID();
  /**
   * <pre>
   *google.protobuf.Timestamp timestamp = 3;//to add a timestamp
   * </pre>
   *
   * <code>string buildingID = 2;</code>
   */
  com.google.protobuf.ByteString
      getBuildingIDBytes();
}
