// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: livemonitor.proto

package ds.livemonitor;

public interface waterReadingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livemonitor.waterReadingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 waterReading = 1;</code>
   */
  int getWaterReading();

  /**
   * <code>int32 buildingID = 2;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 date = 3;</code>
   */
  int getDate();
}
