// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface buildingIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.buildingIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 energyReading = 2;</code>
   */
  int getEnergyReading();
}
