// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface monitoringResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.monitoringResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string exceedMessage = 1;</code>
   */
  java.lang.String getExceedMessage();
  /**
   * <code>string exceedMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getExceedMessageBytes();
}
