// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface sendAlertResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.sendAlertResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string alertMessage = 1;</code>
   */
  java.lang.String getAlertMessage();
  /**
   * <code>string alertMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getAlertMessageBytes();

  /**
   * <pre>
   *google.protobuf.Timestamp date = 3;
   * </pre>
   *
   * <code>int32 buildingID = 2;</code>
   */
  int getBuildingID();
}
