// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface sendAlertRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.sendAlertRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 temperatureReading = 2;</code>
   */
  int getTemperatureReading();

  /**
   * <code>int32 energyReading = 3;</code>
   */
  int getEnergyReading();
}
