// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

/**
 * Protobuf type {@code alert.sendAlertResponse}
 */
public  final class sendAlertResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alert.sendAlertResponse)
    sendAlertResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use sendAlertResponse.newBuilder() to construct.
  private sendAlertResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sendAlertResponse() {
    alertMessage_ = "";
    buildingID_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private sendAlertResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            alertMessage_ = s;
            break;
          }
          case 16: {

            buildingID_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.alert.alertImpl.internal_static_alert_sendAlertResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.alert.alertImpl.internal_static_alert_sendAlertResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.alert.sendAlertResponse.class, ds.alert.sendAlertResponse.Builder.class);
  }

  public static final int ALERTMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object alertMessage_;
  /**
   * <code>string alertMessage = 1;</code>
   */
  public java.lang.String getAlertMessage() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      alertMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string alertMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAlertMessageBytes() {
    java.lang.Object ref = alertMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      alertMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BUILDINGID_FIELD_NUMBER = 2;
  private int buildingID_;
  /**
   * <pre>
   *google.protobuf.Timestamp date = 3;
   * </pre>
   *
   * <code>int32 buildingID = 2;</code>
   */
  public int getBuildingID() {
    return buildingID_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getAlertMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, alertMessage_);
    }
    if (buildingID_ != 0) {
      output.writeInt32(2, buildingID_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAlertMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, alertMessage_);
    }
    if (buildingID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, buildingID_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.alert.sendAlertResponse)) {
      return super.equals(obj);
    }
    ds.alert.sendAlertResponse other = (ds.alert.sendAlertResponse) obj;

    boolean result = true;
    result = result && getAlertMessage()
        .equals(other.getAlertMessage());
    result = result && (getBuildingID()
        == other.getBuildingID());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ALERTMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getAlertMessage().hashCode();
    hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingID();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.alert.sendAlertResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.sendAlertResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.alert.sendAlertResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alert.sendAlertResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alert.sendAlertResponse)
      ds.alert.sendAlertResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.alert.sendAlertResponse.class, ds.alert.sendAlertResponse.Builder.class);
    }

    // Construct using ds.alert.sendAlertResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      alertMessage_ = "";

      buildingID_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertResponse_descriptor;
    }

    @java.lang.Override
    public ds.alert.sendAlertResponse getDefaultInstanceForType() {
      return ds.alert.sendAlertResponse.getDefaultInstance();
    }

    @java.lang.Override
    public ds.alert.sendAlertResponse build() {
      ds.alert.sendAlertResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.alert.sendAlertResponse buildPartial() {
      ds.alert.sendAlertResponse result = new ds.alert.sendAlertResponse(this);
      result.alertMessage_ = alertMessage_;
      result.buildingID_ = buildingID_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.alert.sendAlertResponse) {
        return mergeFrom((ds.alert.sendAlertResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.alert.sendAlertResponse other) {
      if (other == ds.alert.sendAlertResponse.getDefaultInstance()) return this;
      if (!other.getAlertMessage().isEmpty()) {
        alertMessage_ = other.alertMessage_;
        onChanged();
      }
      if (other.getBuildingID() != 0) {
        setBuildingID(other.getBuildingID());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.alert.sendAlertResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.alert.sendAlertResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object alertMessage_ = "";
    /**
     * <code>string alertMessage = 1;</code>
     */
    public java.lang.String getAlertMessage() {
      java.lang.Object ref = alertMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alertMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string alertMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAlertMessageBytes() {
      java.lang.Object ref = alertMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alertMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string alertMessage = 1;</code>
     */
    public Builder setAlertMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      alertMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string alertMessage = 1;</code>
     */
    public Builder clearAlertMessage() {
      
      alertMessage_ = getDefaultInstance().getAlertMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string alertMessage = 1;</code>
     */
    public Builder setAlertMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      alertMessage_ = value;
      onChanged();
      return this;
    }

    private int buildingID_ ;
    /**
     * <pre>
     *google.protobuf.Timestamp date = 3;
     * </pre>
     *
     * <code>int32 buildingID = 2;</code>
     */
    public int getBuildingID() {
      return buildingID_;
    }
    /**
     * <pre>
     *google.protobuf.Timestamp date = 3;
     * </pre>
     *
     * <code>int32 buildingID = 2;</code>
     */
    public Builder setBuildingID(int value) {
      
      buildingID_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *google.protobuf.Timestamp date = 3;
     * </pre>
     *
     * <code>int32 buildingID = 2;</code>
     */
    public Builder clearBuildingID() {
      
      buildingID_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alert.sendAlertResponse)
  }

  // @@protoc_insertion_point(class_scope:alert.sendAlertResponse)
  private static final ds.alert.sendAlertResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.alert.sendAlertResponse();
  }

  public static ds.alert.sendAlertResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sendAlertResponse>
      PARSER = new com.google.protobuf.AbstractParser<sendAlertResponse>() {
    @java.lang.Override
    public sendAlertResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new sendAlertResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sendAlertResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<sendAlertResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.alert.sendAlertResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

