// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

/**
 * Protobuf type {@code alert.sendAlertRequest}
 */
public  final class sendAlertRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alert.sendAlertRequest)
    sendAlertRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use sendAlertRequest.newBuilder() to construct.
  private sendAlertRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sendAlertRequest() {
    buildingID_ = 0;
    temperatureReading_ = 0;
    energyReading_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private sendAlertRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            buildingID_ = input.readInt32();
            break;
          }
          case 16: {

            temperatureReading_ = input.readInt32();
            break;
          }
          case 24: {

            energyReading_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.alert.alertImpl.internal_static_alert_sendAlertRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.alert.alertImpl.internal_static_alert_sendAlertRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.alert.sendAlertRequest.class, ds.alert.sendAlertRequest.Builder.class);
  }

  public static final int BUILDINGID_FIELD_NUMBER = 1;
  private int buildingID_;
  /**
   * <code>int32 buildingID = 1;</code>
   */
  public int getBuildingID() {
    return buildingID_;
  }

  public static final int TEMPERATUREREADING_FIELD_NUMBER = 2;
  private int temperatureReading_;
  /**
   * <code>int32 temperatureReading = 2;</code>
   */
  public int getTemperatureReading() {
    return temperatureReading_;
  }

  public static final int ENERGYREADING_FIELD_NUMBER = 3;
  private int energyReading_;
  /**
   * <code>int32 energyReading = 3;</code>
   */
  public int getEnergyReading() {
    return energyReading_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (buildingID_ != 0) {
      output.writeInt32(1, buildingID_);
    }
    if (temperatureReading_ != 0) {
      output.writeInt32(2, temperatureReading_);
    }
    if (energyReading_ != 0) {
      output.writeInt32(3, energyReading_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (buildingID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, buildingID_);
    }
    if (temperatureReading_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, temperatureReading_);
    }
    if (energyReading_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, energyReading_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.alert.sendAlertRequest)) {
      return super.equals(obj);
    }
    ds.alert.sendAlertRequest other = (ds.alert.sendAlertRequest) obj;

    boolean result = true;
    result = result && (getBuildingID()
        == other.getBuildingID());
    result = result && (getTemperatureReading()
        == other.getTemperatureReading());
    result = result && (getEnergyReading()
        == other.getEnergyReading());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingID();
    hash = (37 * hash) + TEMPERATUREREADING_FIELD_NUMBER;
    hash = (53 * hash) + getTemperatureReading();
    hash = (37 * hash) + ENERGYREADING_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyReading();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.alert.sendAlertRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.sendAlertRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.sendAlertRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.sendAlertRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.alert.sendAlertRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alert.sendAlertRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alert.sendAlertRequest)
      ds.alert.sendAlertRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.alert.sendAlertRequest.class, ds.alert.sendAlertRequest.Builder.class);
    }

    // Construct using ds.alert.sendAlertRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buildingID_ = 0;

      temperatureReading_ = 0;

      energyReading_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.alert.alertImpl.internal_static_alert_sendAlertRequest_descriptor;
    }

    @java.lang.Override
    public ds.alert.sendAlertRequest getDefaultInstanceForType() {
      return ds.alert.sendAlertRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.alert.sendAlertRequest build() {
      ds.alert.sendAlertRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.alert.sendAlertRequest buildPartial() {
      ds.alert.sendAlertRequest result = new ds.alert.sendAlertRequest(this);
      result.buildingID_ = buildingID_;
      result.temperatureReading_ = temperatureReading_;
      result.energyReading_ = energyReading_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.alert.sendAlertRequest) {
        return mergeFrom((ds.alert.sendAlertRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.alert.sendAlertRequest other) {
      if (other == ds.alert.sendAlertRequest.getDefaultInstance()) return this;
      if (other.getBuildingID() != 0) {
        setBuildingID(other.getBuildingID());
      }
      if (other.getTemperatureReading() != 0) {
        setTemperatureReading(other.getTemperatureReading());
      }
      if (other.getEnergyReading() != 0) {
        setEnergyReading(other.getEnergyReading());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.alert.sendAlertRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.alert.sendAlertRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int buildingID_ ;
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public int getBuildingID() {
      return buildingID_;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder setBuildingID(int value) {
      
      buildingID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder clearBuildingID() {
      
      buildingID_ = 0;
      onChanged();
      return this;
    }

    private int temperatureReading_ ;
    /**
     * <code>int32 temperatureReading = 2;</code>
     */
    public int getTemperatureReading() {
      return temperatureReading_;
    }
    /**
     * <code>int32 temperatureReading = 2;</code>
     */
    public Builder setTemperatureReading(int value) {
      
      temperatureReading_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temperatureReading = 2;</code>
     */
    public Builder clearTemperatureReading() {
      
      temperatureReading_ = 0;
      onChanged();
      return this;
    }

    private int energyReading_ ;
    /**
     * <code>int32 energyReading = 3;</code>
     */
    public int getEnergyReading() {
      return energyReading_;
    }
    /**
     * <code>int32 energyReading = 3;</code>
     */
    public Builder setEnergyReading(int value) {
      
      energyReading_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 energyReading = 3;</code>
     */
    public Builder clearEnergyReading() {
      
      energyReading_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alert.sendAlertRequest)
  }

  // @@protoc_insertion_point(class_scope:alert.sendAlertRequest)
  private static final ds.alert.sendAlertRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.alert.sendAlertRequest();
  }

  public static ds.alert.sendAlertRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sendAlertRequest>
      PARSER = new com.google.protobuf.AbstractParser<sendAlertRequest>() {
    @java.lang.Override
    public sendAlertRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new sendAlertRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sendAlertRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<sendAlertRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.alert.sendAlertRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

