// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

/**
 * Protobuf type {@code alert.thresholdRequest}
 */
public  final class thresholdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:alert.thresholdRequest)
    thresholdRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use thresholdRequest.newBuilder() to construct.
  private thresholdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private thresholdRequest() {
    buildingID_ = 0;
    temperatureLimit_ = 0;
    energyLimit_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private thresholdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            buildingID_ = input.readInt32();
            break;
          }
          case 16: {

            temperatureLimit_ = input.readInt32();
            break;
          }
          case 24: {

            energyLimit_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.alert.alertImpl.internal_static_alert_thresholdRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.alert.alertImpl.internal_static_alert_thresholdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.alert.thresholdRequest.class, ds.alert.thresholdRequest.Builder.class);
  }

  public static final int BUILDINGID_FIELD_NUMBER = 1;
  private int buildingID_;
  /**
   * <code>int32 buildingID = 1;</code>
   */
  public int getBuildingID() {
    return buildingID_;
  }

  public static final int TEMPERATURELIMIT_FIELD_NUMBER = 2;
  private int temperatureLimit_;
  /**
   * <code>int32 temperatureLimit = 2;</code>
   */
  public int getTemperatureLimit() {
    return temperatureLimit_;
  }

  public static final int ENERGYLIMIT_FIELD_NUMBER = 3;
  private int energyLimit_;
  /**
   * <code>int32 energyLimit = 3;</code>
   */
  public int getEnergyLimit() {
    return energyLimit_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (buildingID_ != 0) {
      output.writeInt32(1, buildingID_);
    }
    if (temperatureLimit_ != 0) {
      output.writeInt32(2, temperatureLimit_);
    }
    if (energyLimit_ != 0) {
      output.writeInt32(3, energyLimit_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (buildingID_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, buildingID_);
    }
    if (temperatureLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, temperatureLimit_);
    }
    if (energyLimit_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, energyLimit_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.alert.thresholdRequest)) {
      return super.equals(obj);
    }
    ds.alert.thresholdRequest other = (ds.alert.thresholdRequest) obj;

    boolean result = true;
    result = result && (getBuildingID()
        == other.getBuildingID());
    result = result && (getTemperatureLimit()
        == other.getTemperatureLimit());
    result = result && (getEnergyLimit()
        == other.getEnergyLimit());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BUILDINGID_FIELD_NUMBER;
    hash = (53 * hash) + getBuildingID();
    hash = (37 * hash) + TEMPERATURELIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getTemperatureLimit();
    hash = (37 * hash) + ENERGYLIMIT_FIELD_NUMBER;
    hash = (53 * hash) + getEnergyLimit();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.alert.thresholdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.thresholdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.thresholdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.thresholdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.thresholdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.alert.thresholdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.alert.thresholdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.thresholdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.thresholdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.alert.thresholdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.alert.thresholdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.alert.thresholdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.alert.thresholdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code alert.thresholdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:alert.thresholdRequest)
      ds.alert.thresholdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.alert.alertImpl.internal_static_alert_thresholdRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.alert.alertImpl.internal_static_alert_thresholdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.alert.thresholdRequest.class, ds.alert.thresholdRequest.Builder.class);
    }

    // Construct using ds.alert.thresholdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      buildingID_ = 0;

      temperatureLimit_ = 0;

      energyLimit_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.alert.alertImpl.internal_static_alert_thresholdRequest_descriptor;
    }

    @java.lang.Override
    public ds.alert.thresholdRequest getDefaultInstanceForType() {
      return ds.alert.thresholdRequest.getDefaultInstance();
    }

    @java.lang.Override
    public ds.alert.thresholdRequest build() {
      ds.alert.thresholdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.alert.thresholdRequest buildPartial() {
      ds.alert.thresholdRequest result = new ds.alert.thresholdRequest(this);
      result.buildingID_ = buildingID_;
      result.temperatureLimit_ = temperatureLimit_;
      result.energyLimit_ = energyLimit_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.alert.thresholdRequest) {
        return mergeFrom((ds.alert.thresholdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.alert.thresholdRequest other) {
      if (other == ds.alert.thresholdRequest.getDefaultInstance()) return this;
      if (other.getBuildingID() != 0) {
        setBuildingID(other.getBuildingID());
      }
      if (other.getTemperatureLimit() != 0) {
        setTemperatureLimit(other.getTemperatureLimit());
      }
      if (other.getEnergyLimit() != 0) {
        setEnergyLimit(other.getEnergyLimit());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.alert.thresholdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.alert.thresholdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int buildingID_ ;
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public int getBuildingID() {
      return buildingID_;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder setBuildingID(int value) {
      
      buildingID_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 buildingID = 1;</code>
     */
    public Builder clearBuildingID() {
      
      buildingID_ = 0;
      onChanged();
      return this;
    }

    private int temperatureLimit_ ;
    /**
     * <code>int32 temperatureLimit = 2;</code>
     */
    public int getTemperatureLimit() {
      return temperatureLimit_;
    }
    /**
     * <code>int32 temperatureLimit = 2;</code>
     */
    public Builder setTemperatureLimit(int value) {
      
      temperatureLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 temperatureLimit = 2;</code>
     */
    public Builder clearTemperatureLimit() {
      
      temperatureLimit_ = 0;
      onChanged();
      return this;
    }

    private int energyLimit_ ;
    /**
     * <code>int32 energyLimit = 3;</code>
     */
    public int getEnergyLimit() {
      return energyLimit_;
    }
    /**
     * <code>int32 energyLimit = 3;</code>
     */
    public Builder setEnergyLimit(int value) {
      
      energyLimit_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 energyLimit = 3;</code>
     */
    public Builder clearEnergyLimit() {
      
      energyLimit_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:alert.thresholdRequest)
  }

  // @@protoc_insertion_point(class_scope:alert.thresholdRequest)
  private static final ds.alert.thresholdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.alert.thresholdRequest();
  }

  public static ds.alert.thresholdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<thresholdRequest>
      PARSER = new com.google.protobuf.AbstractParser<thresholdRequest>() {
    @java.lang.Override
    public thresholdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new thresholdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<thresholdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<thresholdRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.alert.thresholdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

