// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface thresholdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.thresholdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string setStatusMessage = 1;</code>
   */
  java.lang.String getSetStatusMessage();
  /**
   * <code>string setStatusMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getSetStatusMessageBytes();

  /**
   * <code>int32 date = 2;</code>
   */
  int getDate();
}
