// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: alert.proto

package ds.alert;

public interface thresholdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:alert.thresholdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 temperatureLimit = 2;</code>
   */
  int getTemperatureLimit();

  /**
   * <code>int32 energyLimit = 3;</code>
   */
  int getEnergyLimit();
}
