// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public interface buildingIDRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:control.buildingIDRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();
}
