// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public final class controlImpl {
  private controlImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_buildingIDRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_control_buildingIDRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_energyDemandRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_control_energyDemandRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_heatingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_control_heatingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_lightingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_control_lightingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_control_scheduleResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_control_scheduleResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontrol.proto\022\007control\"\'\n\021buildingIDRe" +
      "quest\022\022\n\nbuildingID\030\001 \001(\005\"?\n\023energyDeman" +
      "dRequest\022\022\n\nbuildingID\030\001 \001(\005\022\024\n\014energyDe" +
      "mand\030\002 \001(\005\"(\n\017heatingResponse\022\025\n\rheating" +
      "Action\030\001 \001(\t\"*\n\020lightingResponse\022\026\n\016ligh" +
      "tingAction\030\001 \001(\t\"*\n\020scheduleResponse\022\026\n\016" +
      "scheduleAdvice\030\001 \001(\t2\363\001\n\017controlSchedule" +
      "\022J\n\ngetHeating\022\034.control.energyDemandReq" +
      "uest\032\030.control.heatingResponse\"\000(\0010\001\022L\n\013" +
      "getLighting\022\034.control.energyDemandReques" +
      "t\032\031.control.lightingResponse\"\000(\0010\001\022F\n\013ge" +
      "tSchedule\022\032.control.buildingIDRequest\032\031." +
      "control.scheduleResponse\"\000B\033\n\nds.control" +
      "B\013controlImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_control_buildingIDRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_control_buildingIDRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_control_buildingIDRequest_descriptor,
        new java.lang.String[] { "BuildingID", });
    internal_static_control_energyDemandRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_control_energyDemandRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_control_energyDemandRequest_descriptor,
        new java.lang.String[] { "BuildingID", "EnergyDemand", });
    internal_static_control_heatingResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_control_heatingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_control_heatingResponse_descriptor,
        new java.lang.String[] { "HeatingAction", });
    internal_static_control_lightingResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_control_lightingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_control_lightingResponse_descriptor,
        new java.lang.String[] { "LightingAction", });
    internal_static_control_scheduleResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_control_scheduleResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_control_scheduleResponse_descriptor,
        new java.lang.String[] { "ScheduleAdvice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
