// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public interface energyDemandRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:control.energyDemandRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 buildingID = 1;</code>
   */
  int getBuildingID();

  /**
   * <code>int32 energyDemand = 2;</code>
   */
  int getEnergyDemand();
}
