// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public interface heatingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:control.heatingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string heatingAction = 1;</code>
   */
  java.lang.String getHeatingAction();
  /**
   * <code>string heatingAction = 1;</code>
   */
  com.google.protobuf.ByteString
      getHeatingActionBytes();
}
