// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public interface lightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:control.lightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string lightingAction = 1;</code>
   */
  java.lang.String getLightingAction();
  /**
   * <code>string lightingAction = 1;</code>
   */
  com.google.protobuf.ByteString
      getLightingActionBytes();
}
