// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: control.proto

package ds.control;

public interface scheduleResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:control.scheduleResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scheduleAdvice = 1;</code>
   */
  java.lang.String getScheduleAdvice();
  /**
   * <code>string scheduleAdvice = 1;</code>
   */
  com.google.protobuf.ByteString
      getScheduleAdviceBytes();
}
